### ISSUE TITLE
This Nebula Service has been disabled

### ISSUE THREAD

**Issue by akwin1234** [NebulaServices/Nebula#214] opened 2024-02-01 12:05 UTC
![4BUNnt9](https://github.com/NebulaServices/Nebula/assets/15890770/013ee054-a775-4a26-b8ff-e608d10fefd7)
Please help i am not sure what is causing this issue
this error occures after entering an url or keyword

ip:port/games also showing same error
EDIT: i am binding to 0.0.0.0 and accessing via public IP. can that be an issue?

**Comment by IncognitoTGT** [comment] 2024-02-01 13:33
we've disabled nebula servicessssssssss :snake:

**Comment by IncognitoTGT** [comment] 2024-02-01 13:34
the issue is likely since the service worker didnt register

**Comment by NottPeak** [comment] 2024-02-01 16:03
make sure you have nebula on port 8080 if you use the nginx method (prty sure you can just change it in index.js, haven't checked in a while)

**Comment by akwin1234** [comment] 2024-02-01 18:24
> make sure you have nebula on port 8080 if you use the nginx method (prty sure you can just change it in index.js, haven't checked in a while)

Thanks a lot it worked. i setup reverse proxy in cyberpanel :)
I was wondering if you may help me with 1 small more thing.

Can we modify the content before printing it?
Like i want to remove ads or may be popup scripts or anything else. remove html popups etc
not asking for logic i wonder where to edit. Kinda new to node js.

Once again thanks a ton!

**Comment by NottPeak** [comment] 2024-02-01 20:44
> > make sure you have nebula on port 8080 if you use the nginx method (prty sure you can just change it in index.js, haven't checked in a while)
> 
> Thanks a lot it worked. i setup reverse proxy in cyberpanel :) I was wondering if you may help me with 1 small more thing.
> 
> Can we modify the content before printing it? Like i want to remove ads or may be popup scripts or anything else. remove html popups etc not asking for logic i wonder where to edit. Kinda new to node js.
> 
> Once again thanks a ton!

you could do some stuff with the rewrite code, a slightly easier (not as efficient) approach would be putting some JavaScript code inside the /public/UV/UV.config.js file. anything in there is run on page load (sometimes a couple times when the page loads, add logic to prevent that), so that is useful.

**Closed** 2024-02-01 21:15 UTC
